name: notustohtml
description: Convert the Notus document format to an HTML representation.
version: 0.0.8
homepage: https://github.com/JacobWrenn/notustohtml

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  notus: ^1.0.0-dev.4.0
  quill_delta: ^2.0.0
  html: ^0.14.0

dev_dependencies:
  test:
